// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVCsScD5sTbXkhAYHaDOJJpbhc4pXtW0',
    appId: '1:928212580002:android:eba3deb573bcc9b95609fb',
    messagingSenderId: '928212580002',
    projectId: 'task-84c92',
    storageBucket: 'task-84c92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMpZ2s0DAbihuGsfgqCqfY2Vn3nWJyMA',
    appId: '1:928212580002:ios:15718bf13cc383745609fb',
    messagingSenderId: '928212580002',
    projectId: 'task-84c92',
    storageBucket: 'task-84c92.appspot.com',
    androidClientId: '928212580002-cfs633psts0oem3gk8p0490ii5t104o0.apps.googleusercontent.com',
    iosClientId: '928212580002-ei3rvegh0m8d38np45h6l96svr50k7pe.apps.googleusercontent.com',
    iosBundleId: 'com.seven.task',
  );
}
